Dynamic buffer calculation
Azure/sonic-swss-common pull request #361
Opened 2020-07-01 10:00 UTC by stephenxs

1. Database schema updates.
2. Move the json file parsing from swss to swss-common.

2020-09-10 15:59 UTC, neethajohn requested changes

2020-11-16 01:15 UTC, stephenxs commented on common/json.cpp
> +                    kfvOp(cur_db_item) = cur_obj.get<string>();
This is a redundant sentence and has been removed.

2020-11-16 07:26 UTC, liat-grozovik requested changes
Is there any other doc file which schema should be updated as well?

2020-11-16 07:26 UTC, liat-grozovik commented on common/json.cpp
> +bool JSon::loadJsonFromFile(ifstream &fs, vector<KeyOpFieldsValuesTuple> &db_items)
can you please add some documentation explaining the motivation of this and why it is needed?
explanation of the return code and the output can also be nice and what is the file type expected.

2020-11-16 07:26 UTC, liat-grozovik commented on common/json.h
> +    static const int el_count = 2;
what is 2 stands for as the default?

2020-11-16 07:26 UTC, liat-grozovik commented on common/schema.h
>  /***** TO BE REMOVED *****/
although this is not news, what should be removed?

2020-11-16 09:40 UTC, stephenxs commented on common/json.cpp
> +bool JSon::loadJsonFromFile(ifstream &fs, vector<KeyOpFieldsValuesTuple> &db_items)
Done. add some description in the header.

2020-11-16 09:41 UTC, stephenxs commented on common/json.h
> +    static const int el_count = 2;
the number of elements in each object: 2 stands for the data and the op.
comment added for it as well

2020-11-16 09:42 UTC, stephenxs commented on common/schema.h
>  /***** TO BE REMOVED *****/
I can't say for sure, but I think probably it should be the following QoS tables.
The qosorch consumes CONFIG_DB table and the tables in APPL_DB aren't used.

2020-11-16 10:34 UTC, liat-grozovik submitted a review, later dismissed

2020-11-16 10:34 UTC, liat-grozovik commented
@neetha please review and provide your feedback. this PR is needed to be the first to be merged so other related PRs can be tested properly in Jenkins PR CI

2020-11-20 02:49 UTC, neethajohn commented on common/json.cpp
> +                    }
Where is the 'OP' field getting parsed?

2020-11-20 10:16 UTC, stephenxs commented on common/json.cpp
> +                    }
Added that logic. If `op` isn't `SET`, ignore the item and log an error.

2020-11-20 17:13 UTC, neethajohn approved these changes

2020-11-24 10:56 UTC, liat-grozovik approved these changes

2020-11-24 11:42 UTC, liat-grozovik approved these changes

2020-11-24 11:43 UTC, liat-grozovik commented
@neethajohn your approval was lost with the last push. can you please approve and merge?

2020-11-24 18:49 UTC, neethajohn approved these changes

2020-11-30 06:57 UTC, liat-grozovik commented
@qiluo-msft can you please sign off?

2020-11-30 07:33 UTC, qiluo-msft commented on common/json.cpp
> +bool JSon::loadJsonFromFile(ifstream &fs, vector<KeyOpFieldsValuesTuple> &db_items)
>fs [](start = 38, length = 2)

What happens if `fs` is already `close()` or in bad status before enter this function?

2020-11-30 07:34 UTC, qiluo-msft commented on common/json.cpp
> +    fs >> json_array;
>fs >> json_array; [](start = 4, length = 17)

What happens if there is IO error, or invalid json format? Will any case throw exception?

2020-11-30 07:36 UTC, qiluo-msft commented on common/json.cpp
> +            db_items.push_back(KeyOpFieldsValuesTuple());
>push_back [](start = 21, length = 9)

`emplace_back` will be better, one less temp object.

2020-11-30 07:37 UTC, qiluo-msft commented on common/json.cpp
> +            auto &cur_db_item = db_items[db_items.size() - 1];
>db_items[db_items.size() - 1] [](start = 32, length = 29)

`db_items.back()`

2020-11-30 07:39 UTC, qiluo-msft commented on common/json.cpp
> +            for (nlohmann::json::iterator child_it = arr_item.begin(); child_it != arr_item.end(); child_it++) {
>nlohmann::json::iterator [](start = 17, length = 24)

auto

2020-11-30 07:40 UTC, qiluo-msft commented on common/json.cpp
> +            for (nlohmann::json::iterator child_it = arr_item.begin(); child_it != arr_item.end(); child_it++) {
>{ [](start = 111, length = 1)

Move `}` to next line

2020-11-30 07:41 UTC, qiluo-msft commented on common/json.cpp
> +                        SWSS_LOG_ERROR("Child elements'op field must be SET, but got %s, ignored", op.c_str());
>op [](start = 55, length = 2)

Add one blank before?

2020-11-30 07:42 UTC, qiluo-msft commented on common/json.cpp
> +                        SWSS_LOG_ERROR("Child elements'op field must be SET, but got %s, ignored", op.c_str());
>must be [](start = 64, length = 7)

Why must be? Is there any document?

2020-11-30 07:42 UTC, qiluo-msft requested changes
As comments

2020-12-01 00:48 UTC, stephenxs commented on common/json.cpp
> +    fs >> json_array;
There can be an exception which will be catched by the caller.

2020-12-01 00:48 UTC, stephenxs commented on common/json.cpp
> +            db_items.push_back(KeyOpFieldsValuesTuple());
fixed

2020-12-01 00:48 UTC, stephenxs commented on common/json.cpp
> +            auto &cur_db_item = db_items[db_items.size() - 1];
fixed

2020-12-01 00:48 UTC, stephenxs commented on common/json.cpp
> +            for (nlohmann::json::iterator child_it = arr_item.begin(); child_it != arr_item.end(); child_it++) {
fixed

2020-12-01 00:49 UTC, stephenxs commented on common/json.cpp
> +            for (nlohmann::json::iterator child_it = arr_item.begin(); child_it != arr_item.end(); child_it++) {
fixed

2020-12-01 00:49 UTC, stephenxs commented on common/json.cpp
> +                        SWSS_LOG_ERROR("Child elements'op field must be SET, but got %s, ignored", op.c_str());
fixed

2020-12-01 01:05 UTC, stephenxs commented on common/json.cpp
> +                        SWSS_LOG_ERROR("Child elements'op field must be SET, but got %s, ignored", op.c_str());
The are two operations defined: `SET` and `DEL`. The `DEL` doesn't make sense here because it's about to insert the items into the database.

2020-12-01 02:18 UTC, qiluo-msft commented on common/json.cpp
> +            db_items.emplace_back(KeyOpFieldsValuesTuple());
>KeyOpFieldsValuesTuple [](start = 34, length = 22)

You can actually `emplace_back()`. It's like combining ctor and push into one statement.

2020-12-01 02:19 UTC, qiluo-msft commented on common/json.cpp
> +                        kfvFieldsValues(cur_db_item).emplace_back(FieldValueTuple(field_str, value_str));
>emplace_back(FieldValueTuple(field_str, value_str)) [](start = 53, length = 51)

`emplace_back(field_str, value_str)`

2020-12-01 02:20 UTC, qiluo-msft commented on common/json.cpp
> +                        SWSS_LOG_ERROR("Child elements'op field must be SET, but got %s, ignored", op.c_str());
Sorry, I mean `elements' op`, ie. before `op`

---
In reply to: [532396054](https://github.com/Azure/sonic-swss-common/pull/361#discussion_r532396054) [](ancestors = 532396054)

2020-12-01 02:22 UTC, qiluo-msft commented on common/json.cpp
> +                        SWSS_LOG_ERROR("Child elements'op field must be SET, but got %s, ignored", op.c_str());
It depends on the use case. In general, it still makes sense to support all the `op` options.

---
In reply to: [532396572](https://github.com/Azure/sonic-swss-common/pull/361#discussion_r532396572) [](ancestors = 532396572)

2020-12-01 02:23 UTC, qiluo-msft commented on common/json.cpp
> +    fs >> json_array;
Then better to return false instead of throwing?

---
In reply to: [532393445](https://github.com/Azure/sonic-swss-common/pull/361#discussion_r532393445) [](ancestors = 532393445)

2020-12-01 02:25 UTC, stephenxs commented on common/json.cpp
> +                        SWSS_LOG_ERROR("Child elements'op field must be SET, but got %s, ignored", op.c_str());
sounds reasonable. 
so we just need to check whether it's `SET` or `DEL` and log an error only if neither matched. and move the test to the caller.

2020-12-01 02:27 UTC, stephenxs commented on common/json.cpp
> +    fs >> json_array;
OK.
In that case, can we declare the method as "noexcept"?

2020-12-01 05:57 UTC, qiluo-msft commented on common/json.cpp
> +    catch (...)
>catch (...) [](start = 4, length = 11)

Do not catch general exception except in most outmost level. Catch by as specific type as possible. I guess there are two types: fstream exception and json deserialization exception.
Also need to log exception messages.

2020-12-02 01:42 UTC, stephenxs commented on common/json.cpp
> +    catch (...)
It can throw the following exceptions:
- bad_alloc in constructors in case of insufficient memory
- domain_error, out_of_range and invalid_argument in case of the syntax error
To cover them all, I tend to catch the `std::exception`. even though it indeed is a big set but it's the most concrete exception which covers all the possibilities.
@qiluo-msft how do you think?

2020-12-02 03:33 UTC, qiluo-msft commented on common/json.cpp
> +    catch (...)
`exception` is still too general. So my comment still applies. Could you break it down to more specific exception type or multiple exception types?

---
In reply to: [533090214](https://github.com/Azure/sonic-swss-common/pull/361#discussion_r533090214) [](ancestors = 533090214)

2020-12-02 04:36 UTC, stephenxs commented on common/json.cpp
> +    catch (...)
ok.
for `domain_error`, `out_of_range` and `invalid_argument`, they are all derived from `logic_error` so we can catch it.
for `bad_alloc`, it needs to be handled separately.

2020-12-02 05:00 UTC, stephenxs commented on common/json.cpp
> +    catch (...)
@qiluo-msft done.

2020-12-02 06:29 UTC, qiluo-msft commented on common/json.cpp
> +        SWSS_LOG_ERROR("Unable to parse json from the imput stream: %s", e.what());
>imput [](start = 54, length = 5)

`input`

2020-12-02 06:35 UTC, stephenxs commented on common/json.cpp
> +        SWSS_LOG_ERROR("Unable to parse json from the imput stream: %s", e.what());
fixed

2020-12-02 06:41 UTC, qiluo-msft approved these changes

2020-12-02 10:25 UTC, liat-grozovik commented
@qiluo-msft can you please merge?

2020-12-02 10:26 UTC, liat-grozovik approved these changes

2020-12-02 18:08 UTC, merged