ASIC internal temperature sensors support
Azure/sonic-swss-common pull request #419
Opened 2020-11-23 10:26 UTC by santhosh-kt

ASIC internal temperature sensors support

More details:
Azure/sonic-swss#

Details if related
HLD Location: https://github.com/Azure/SONiC/blob/master/doc/asic_thermal_monitoring_hld.md

2020-11-24 23:47 UTC, jleveque requested changes

2020-11-24 23:47 UTC, jleveque commented on common/schema.h
> +#define ASIC_SENSORS_TABLE_NAME	            "SENSORS"
Please left-align `"SENSORS"` with `"MUX_CABLE_TABLE"`

2020-11-24 23:47 UTC, jleveque commented on common/schema.h
> +#define CFG_ASIC_SENSORS_TABLE_NAME	  "ASIC_SENSORS"
Please left-align `"ASIC_SENSORS"` with `"VLAN_SUB_INTERFACE"`

2020-11-25 05:01 UTC, jleveque approved these changes

2020-11-25 05:46 UTC, qiluo-msft commented on common/schema.h
> +#define ASIC_SENSORS_TABLE_NAME             "SENSORS"
>ASIC_SENSORS_TABLE_NAME [](start = 8, length = 23)

This is not in design doc.

2020-11-25 05:55 UTC, santhosh-kt commented on common/schema.h
> +#define ASIC_SENSORS_TABLE_NAME             "SENSORS"
My Apology.
I had two different clients with different table names(One for prototype and another for PR).
Didn't update the table name back.
Will update the thread.

2020-11-25 05:59 UTC, santhosh-kt commented on common/schema.h
> +#define ASIC_SENSORS_TABLE_NAME             "SENSORS"
Now ASIC_TEMPERATURE_INFO_TABLE_NAME is matching with Azure/sonic-swss#1517

2020-11-25 18:58 UTC, qiluo-msft approved these changes

2020-11-25 19:16 UTC, jleveque approved these changes

2020-11-25 19:16 UTC, merged

2020-11-25 19:20 UTC, jleveque commented
Submodule update PR: https://github.com/Azure/sonic-buildimage/pull/6042

2020-12-02 01:57 UTC, prsunny commented on common/schema.h
> +#define ASIC_TEMPERATURE_INFO_TABLE_NAME    "ASIC_TEMPERATURE_INFO"
Sorry for the late comment - This should not belong here as the section is for APP DB entries. From the [usage](https://github.com/Azure/sonic-swss/blob/730e984e62b3bd47c22168e312c25bda2e850d28/orchagent/switchorch.cpp#L41), it looks to be part of STATE DB entries. 

Is it possible to correct this?