Add utility for string and redis
Azure/sonic-swss-common pull request #434
Opened 2020-12-22 14:33 UTC by Pterosaur

Signed-off-by: Ze Gan <ganze718@gmail.com>

2020-12-22 15:54 UTC, caizhenghui-juniper approved these changes

2020-12-22 18:32 UTC, qiluo-msft commented on common/stringutility.h
> +#ifndef __STRINGUTILITY__
>__STRINGUTILITY__ [](start = 8, length = 17)

The use of two underscores (`__') in identifiers is reserved for the compiler's internal use according to the ANSI-C standard.
Suggest use `#pragma once`

2020-12-22 19:01 UTC, qiluo-msft commented on common/stringutility.h
> +    std::istringstream istream(input);
>istream [](start = 23, length = 7)

How is delimiter used in the input stream?

2020-12-22 19:02 UTC, qiluo-msft commented on common/stringutility.h
> +std::string join(char delimiter, const T &input)
>delimiter [](start = 22, length = 9)

Not used?

2020-12-22 19:25 UTC, qiluo-msft commented on common/stringutility.h
> +bool split(const std::string &input, char delimiter, T &output)
>split [](start = 5, length = 5)

Did you try boost split and join functions?

2020-12-22 19:51 UTC, qiluo-msft commented on common/stringutility.cpp
> +    std::string buffer = istream.str();
>str [](start = 33, length = 3)

Assume istream is extremely long, calling `str()` is not efficient.

2020-12-22 19:52 UTC, qiluo-msft commented on common/stringutility.cpp
> +    if (buffer == "true" || buffer == "1")
>buffer [](start = 8, length = 6)

You did not consume the string in istream

2020-12-22 20:03 UTC, qiluo-msft commented on common/stringutility.cpp
> +bool swss::hex_to_binary(
>hex_to_binary [](start = 11, length = 13)

It would be easier if you use boost `unhex` or `stringstream` + `std::hex`

2020-12-22 20:07 UTC, qiluo-msft commented on common/stringutility.cpp
> +        snprintf(&output[i * 2], 3, "%02X", input[i]);
>output [](start = 18, length = 6)

You will write one more `\0` into `s`.

2020-12-22 20:09 UTC, qiluo-msft commented on common/stringutility.cpp
> +std::string swss::binary_to_hex(const void *buffer, size_t length)
>binary_to_hex [](start = 18, length = 13)

It would be easier if you use boost `hex` or `stringstream` + `std::hex`

2020-12-22 20:09 UTC, qiluo-msft commented on common/stringutility.cpp
> +
Remove extra blank line.

2020-12-22 20:12 UTC, qiluo-msft commented on common/redisutility.h
> +static bool get_value(
>get_value [](start = 12, length = 9)

Better name: fvGetValue

2020-12-22 20:13 UTC, qiluo-msft commented on common/redisutility.h
> +        ::tolower);
>tolower [](start = 10, length = 7)

What is the use case of case-insensitive comparison?

2020-12-22 20:14 UTC, qiluo-msft commented on common/rediscommand.h
> +#include <vector>
>vector [](start = 10, length = 6)

This is a valid and obvious fix. You may submit a small standalone PR for it.

2020-12-22 20:14 UTC, qiluo-msft requested changes
As comments

2020-12-23 02:49 UTC, Pterosaur commented on common/stringutility.h
> +    std::istringstream istream(input);
This function is as a terminator to `bool split(const std::string &input, char delimiter, T &output, Args &... args)`, so I assume the last part of input string should not include any delimiter.

2020-12-23 02:52 UTC, Pterosaur commented on common/stringutility.h
> +std::string join(char delimiter, const T &input)
Yes, it isn't used. It's a terminator of `std::string join(char delimiter, const T &input, const Args &... args)`. So this parameters is to adapt the recursive style.
I will add qualifier, `__attribute__((unused))`, before this parameter delimiter.

2020-12-23 03:02 UTC, Pterosaur commented on common/stringutility.h
> +bool split(const std::string &input, char delimiter, T &output)
I want to directly get some variables with expected type from the input string. I think boost split can just help us to split string into vector<string>.Meanwhile  I know we have had a helper `tokenize` can split string like boost split.
So what's your suggestion about replacing my code to boost split or tokenize and then convert vector<string> to expected type? or just keep it as it is.

2020-12-23 03:14 UTC, Pterosaur commented on common/redisutility.h
> +        ::tolower);
I'm not sure, according to my understanding, if the field name is case-insensitive it will be better to use.
Do you have any concern.

2020-12-23 03:15 UTC, Pterosaur commented on common/rediscommand.h
> +#include <vector>
https://github.com/Azure/sonic-swss-common/pull/435

2020-12-23 03:15 UTC, qiluo-msft commented on common/stringutility.h
> +bool split(const std::string &input, char delimiter, T &output)
Suggest you reuse existing function or common libraries (stl/boost/etc) first. If you find anything missing, try improve it based on existing ones by wrapping or preprocessing.
The last resort is to implement yourself.

---
In reply to: [547464854](https://github.com/Azure/sonic-swss-common/pull/434#discussion_r547464854) [](ancestors = 547464854)

2020-12-23 06:43 UTC, Pterosaur commented on common/stringutility.h
> +#ifndef __STRINGUTILITY__
Done

2020-12-23 06:43 UTC, Pterosaur commented on common/stringutility.h
> +bool split(const std::string &input, char delimiter, T &output)
Done

2020-12-23 06:43 UTC, Pterosaur commented on common/stringutility.cpp
> +    std::string buffer = istream.str();
Done

2020-12-23 06:43 UTC, Pterosaur commented on common/stringutility.cpp
> +    if (buffer == "true" || buffer == "1")
Done

2020-12-23 06:43 UTC, Pterosaur commented on common/stringutility.cpp
> +bool swss::hex_to_binary(
Done

2020-12-23 06:44 UTC, Pterosaur commented on common/stringutility.cpp
> +        snprintf(&output[i * 2], 3, "%02X", input[i]);
Done

2020-12-23 06:44 UTC, Pterosaur commented on common/stringutility.cpp
> +std::string swss::binary_to_hex(const void *buffer, size_t length)
Done

2020-12-23 06:44 UTC, Pterosaur commented on common/stringutility.cpp
> +
Done

2020-12-23 06:44 UTC, Pterosaur commented on common/redisutility.h
> +static bool get_value(
Done

2020-12-23 07:43 UTC, qiluo-msft commented on common/stringutility.h
> +bool split(const std::string &input, char delimiter, T &output)
Sorry for misleading. I mean the caller could just use `tokenize` or any common library function instead of your `split`.
They are roughly the same, I don't see significant benefit added in the `split`.

---
In reply to: [547616749](https://github.com/Azure/sonic-swss-common/pull/434#discussion_r547616749) [](ancestors = 547616749,547464854)

2020-12-23 07:52 UTC, qiluo-msft commented on common/stringutility.h
> +    istream >> output;
I see you want to support any type `T`. However the construction of istringstream seems inefficient if you have a long vector. Possible to optimize for each type, like `stol` for `long`.
What is the use case? And how critical the new function required?

2020-12-23 08:01 UTC, qiluo-msft commented on common/stringutility.cpp
> +        std::insert_iterator<std::string>(s, s.end()));
>std::insert_iterator<std::string>(s, s.end()) [](start = 8, length = 45)

Better to use `std::back_inserter(s)`

2020-12-23 08:09 UTC, qiluo-msft commented on common/stringutility.cpp
> +    catch(const boost::algorithm::not_enough_input &e)
>boost::algorithm::not_enough_input &e) [](start = 16, length = 38)

It's more efficient to check even number before `unhex`, so no need to catch.

2020-12-23 08:12 UTC, qiluo-msft commented on common/stringutility.h
> +std::string join(char delimiter, const T &input)
Got it. Then better to remove the variable name and just use `char`. No need to add attribute.

---
In reply to: [547451799](https://github.com/Azure/sonic-swss-common/pull/434#discussion_r547451799) [](ancestors = 547451799)

2020-12-23 08:13 UTC, qiluo-msft commented on common/stringutility.h
> +    if (begin_itr == end_itr)
>begin_itr [](start = 8, length = 9)

`begin` `end` are more readable?

2020-12-23 08:14 UTC, qiluo-msft commented on common/stringutility.cpp
> +    if (hex_str.length() > (buffer_length * 2))
>> [](start = 25, length = 1)

The use case for `>` is a surprise to me. How is the use case like? Is it better to return false?

2020-12-23 08:47 UTC, Pterosaur commented on common/stringutility.h
> +bool split(const std::string &input, char delimiter, T &output)
I want to a helper function that I can directly get the variable with expected type. If the caller use tokenize or split in boost, I have to explicitly convert the string to target type at many positions.

2020-12-23 09:21 UTC, Pterosaur commented on common/stringutility.h
> +    istream >> output;
Agree. I replace istringstream by boost lexical_cast

2020-12-23 09:22 UTC, Pterosaur commented on common/stringutility.cpp
> +        std::insert_iterator<std::string>(s, s.end()));
Done

2020-12-23 09:22 UTC, Pterosaur commented on common/stringutility.h
> +    if (begin_itr == end_itr)
Done

2020-12-23 09:29 UTC, Pterosaur commented on common/stringutility.cpp
> +    if (hex_str.length() > (buffer_length * 2))
How about to change `>` to `!=`?

2020-12-23 22:37 UTC, prsunny commented
@Pterosaur , could you please provide some examples in description on usage of the utility?

2020-12-24 03:57 UTC, Pterosaur commented
> @Pterosaur , could you please provide some examples in description on usage of the utility?

Add some examples in the description of this PR, please check it.

2020-12-24 05:26 UTC, qiluo-msft commented on common/redisutility.h
> +        ::tolower);
So better not to support unused feature and treat comparison case-sensitive.

---
In reply to: [547486695](https://github.com/Azure/sonic-swss-common/pull/434#discussion_r547486695) [](ancestors = 547486695)

2020-12-24 05:27 UTC, qiluo-msft commented on common/stringutility.h
> +std::string join(char , const T &input)
>  [](start = 21, length = 1)

Remove the blank after char.

2020-12-24 05:29 UTC, qiluo-msft commented on common/stringutility.cpp
> +    if (hex_str.length() > (buffer_length * 2))
That looks better.

---
In reply to: [547789357](https://github.com/Azure/sonic-swss-common/pull/434#discussion_r547789357) [](ancestors = 547789357)

2020-12-24 05:42 UTC, qiluo-msft commented on common/redisutility.h
> +        ::tolower);
If you want to support both mode:
1. make case-sensitive an option parameter, default to sensitive.
2. don't use tolower in comparison, there may be some std library
3. try make code readable.

---
In reply to: [548387904](https://github.com/Azure/sonic-swss-common/pull/434#discussion_r548387904) [](ancestors = 548387904,547486695)

2020-12-24 06:02 UTC, qiluo-msft commented on common/redisutility.h
> +static bool fvtGetValue(
>fvtGetValue [](start = 12, length = 11)

Better to have 2 functions: getValue extract a string, then another function to cast.

2020-12-24 06:03 UTC, qiluo-msft commented on common/stringutility.h
> +T lexical_cast(const std::string &str)
>lexical_cast [](start = 2, length = 12)

`cast`

2020-12-24 06:14 UTC, qiluo-msft commented on common/stringutility.cpp
> +    bool &b)
This function is not very useful because we don't have a flexible schema definition. If it is ambiguous in schema, we need to fix schema itself.

2020-12-24 06:21 UTC, qiluo-msft commented on common/stringutility.h
> +bool split(const std::string &input, char delimiter, T &output)
>T &output) [](start = 53, length = 10)

Discussed offline, we need to separate split strings function and cast tuple function.

2020-12-24 06:23 UTC, qiluo-msft commented on common/stringutility.h
> +    ostream << input << delimiter << join(delimiter, args...);
>ostream [](start = 4, length = 7)

Optimize ostream in recursive.

2020-12-24 06:34 UTC, qiluo-msft commented on common/stringutility.cpp
> +    if (hex_str.length() % 2 != 0)
No need to check even now.

2020-12-24 06:38 UTC, qiluo-msft commented on common/stringutility.cpp
> +        SWSS_LOG_ERROR("Invalid hex string %s", hex_str.c_str());
>SWSS_LOG_ERROR [](start = 8, length = 14)

DEBUG

2020-12-24 06:38 UTC, qiluo-msft commented on common/stringutility.cpp
> +    auto _buffer = static_cast<const std::uint8_t *>(buffer);
>_buffer [](start = 9, length = 7)

buf

2020-12-24 12:03 UTC, Pterosaur commented on common/redisutility.h
> +        ::tolower);
Done

2020-12-24 12:03 UTC, Pterosaur commented on common/stringutility.h
> +std::string join(char , const T &input)
Done

2020-12-24 12:05 UTC, Pterosaur commented on common/stringutility.cpp
> +    auto _buffer = static_cast<const std::uint8_t *>(buffer);
Done

2020-12-24 12:05 UTC, Pterosaur commented on common/stringutility.cpp
> +        SWSS_LOG_ERROR("Invalid hex string %s", hex_str.c_str());
Done

2020-12-24 12:05 UTC, Pterosaur commented on common/stringutility.cpp
> +    if (hex_str.length() % 2 != 0)
Done

2020-12-24 12:05 UTC, Pterosaur commented on common/stringutility.h
> +    ostream << input << delimiter << join(delimiter, args...);
Done

2020-12-24 12:05 UTC, Pterosaur commented on common/stringutility.h
> +bool split(const std::string &input, char delimiter, T &output)
Done

2020-12-24 12:05 UTC, Pterosaur commented on common/stringutility.cpp
> +    bool &b)
Done

2020-12-24 12:05 UTC, Pterosaur commented on common/stringutility.h
> +T lexical_cast(const std::string &str)
Done

2020-12-24 12:05 UTC, Pterosaur commented on common/redisutility.h
> +static bool fvtGetValue(
Done

2020-12-24 19:31 UTC, qiluo-msft commented on tests/redisutility_ut.cpp
> +    auto si = swss::fvtGetValue(fvt, "int");
>fvt [](start = 20, length = 3)

`fvs` is for a vector of tuples. So it is a better name.
`fvt` is for a tuple.

2020-12-24 19:41 UTC, qiluo-msft commented on common/redisutility.h
> +    FieldNameStrategy strategy = FieldNameStrategy::CASE_SENSITIVE)
>FieldNameStrategy [](start = 4, length = 17)

Since there are only 2 options, use a bool?

2020-12-24 19:42 UTC, qiluo-msft commented on common/redisutility.h
> +                is_equal = boost::equals(fvField(*itr), field);
>boost::equals [](start = 27, length = 13)

Use `==` for better readability?

2020-12-24 19:48 UTC, qiluo-msft commented on common/redisutility.h
> +    return boost::optional<std::string>();
>boost::optional<std::string>() [](start = 11, length = 30)

`boost::none`

2020-12-24 19:50 UTC, qiluo-msft commented on common/redisutility.h
> +    SWSS_LOG_DEBUG("Cannot find field : %s", field.c_str());
>SWSS_LOG_DEBUG [](start = 4, length = 14)

This is obvious from the return value, no need to logging anything inside this function, including above `SWSS_LOG_ENTER`

2020-12-24 20:00 UTC, qiluo-msft commented on common/stringutility.h
> +    SWSS_LOG_ENTER();
>SWSS_LOG_ENTER [](start = 4, length = 14)

Suggest no log simple functions.

2020-12-24 20:01 UTC, qiluo-msft commented on common/stringutility.h
> +void cast(const std::string &str, T &t)
>cast [](start = 5, length = 4)

`static inline`

2020-12-24 21:02 UTC, qiluo-msft commented on tests/redisutility_ut.cpp
> +    ASSERT_NO_THROW(swss::cast({si.get(), sb.get(), ss.get()}, i, b, s));
>si.get(), sb.get(), ss.get() [](start = 32, length = 28)

`*si, *sb, *ss` will be shorter.

2020-12-24 23:06 UTC, qiluo-msft commented on common/schema.h
> +#define TRUE_STRING "true"
>"true" [](start = 20, length = 6)

Align with above lines

2020-12-24 23:10 UTC, qiluo-msft commented on common/stringutility.h
> +void cast(
>cast [](start = 5, length = 4)

These functions are not expected to be used by applications directly. So suggest move them into another namespace `swss::xxxx_details::`

2020-12-24 23:12 UTC, qiluo-msft commented on common/stringutility.h
> +void cast(const std::vector<std::string> &strs, T &t, Args &... args)
>cast [](start = 5, length = 4)

After 2nd thought, I see `cast` is too ambiguous. I propose the name `swss::lexical_convert`.

2020-12-24 23:13 UTC, qiluo-msft commented on common/stringutility.h
> +void join(std::ostringstream &ostream, char, const T &t)
>join [](start = 5, length = 4)

These functions are not expected to be used by applications directly. So suggest move them into another namespace swss::xxxx_details::

2020-12-24 23:15 UTC, qiluo-msft commented on common/stringutility.h
> +    T &value)
Don't break lines for short parameter list.

2020-12-24 23:21 UTC, qiluo-msft commented on common/redisutility.h
> +static inline boost::optional<std::string> fvtGetValue(
>inline [](start = 7, length = 6)

Don't inline non-trivial functions. Separate into cpp will make dependent project easy to build.

2020-12-24 23:23 UTC, qiluo-msft commented on common/redisutility.h
> +static inline boost::optional<std::string> fvtGetValue(
Then make the include headers as minimal as possible. Only for function declaration purpose, not for function implementation.

---
In reply to: [548762018](https://github.com/Azure/sonic-swss-common/pull/434#discussion_r548762018) [](ancestors = 548762018)

2020-12-24 23:25 UTC, qiluo-msft commented on common/stringutility.h
> +static inline void cast(const std::string &str, bool &b)
>cast [](start = 19, length = 4)

If it is ambiguous in schema, maybe we can improve schema to use only 0/1.
Then we don't need this flexible bool casting.

2020-12-25 02:06 UTC, Pterosaur commented on common/stringutility.h
> +static inline void cast(const std::string &str, bool &b)
I think to support "true"/"false" in schema is useful because it can be consistent with SONiC doc, like https://github.com/Azure/SONiC/blob/b16791f3ca16398153556f40b11831cfbb6aba79/thermal-control-design.md.
![image](https://user-images.githubusercontent.com/18609639/103114136-75303900-4698-11eb-829d-277f6bc13d37.png)

If we will revise all existed bool to 0/1, otherwise, I think, it will be a little bit confuse to a new developer about how to declare a bool.

2020-12-25 02:08 UTC, Pterosaur commented on common/stringutility.h
> +void cast(const std::vector<std::string> &strs, T &t, Args &... args)
Agree

2020-12-25 03:22 UTC, qiluo-msft commented on common/stringutility.h
> +static inline void cast(const std::string &str, bool &b)
Discussed offline. I anticipate a general solution will be:

1. support any customized pair, even like down/up -> 0/1
2. never mix pair, like up/enable

We could achieve this by new classes, which could be implicitly convert to bool. They are different only when serialize/deserialize.

---
In reply to: [548762444](https://github.com/Azure/sonic-swss-common/pull/434#discussion_r548762444) [](ancestors = 548762444)

2020-12-25 07:07 UTC, Pterosaur commented on common/stringutility.h
> +static inline void cast(const std::string &str, bool &b)
Done

2020-12-28 01:55 UTC, qiluo-msft commented on common/stringutility.h
> +// }
Remove unused code

2020-12-28 02:00 UTC, qiluo-msft commented on common/boolean.h
> +    static const std::string ALPHA_TRUE;
>ALPHA_TRUE [](start = 29, length = 10)

TRUE_STRING

2020-12-28 02:00 UTC, qiluo-msft commented on common/boolean.h
> +    static const std::string ALPHA_FALSE;
>ALPHA_FALSE [](start = 29, length = 11)

FALSE_STRING

2020-12-28 02:01 UTC, qiluo-msft commented on common/boolean.cpp
> +const std::string swss::AlphaBoolean::ALPHA_FALSE = "false";
You may inline the super short functions and member constants, to it will be optimized out.

2020-12-28 02:04 UTC, qiluo-msft commented on common/boolean.cpp
> +    out << (b ? swss::AlphaBoolean::ALPHA_TRUE : swss::AlphaBoolean::ALPHA_FALSE);
>swss::AlphaBoolean::ALPHA_TRUE [](start = 16, length = 30)

`b.TRUE_STRING`
If you improve the classes, you may write a generic `<<` for all `Boolean` and its subclasses.

2020-12-28 02:09 UTC, qiluo-msft commented on common/stringutility.h
> +// static inline void lexical_convert(const std::string &str, bool &b)
>lexical_convert [](start = 22, length = 15)

Do you need to implement lexical_convert for AlphaBoolean?
If there is a default one, is it implemented by stringstream? If yes, I think you can provide a simpler one by overload here.

2020-12-28 02:10 UTC, qiluo-msft commented on common/boolean.cpp
> +std::istream &swss::operator>>(std::istream &in, swss::AlphaBoolean &b)
>>> [](start = 28, length = 2)

For this special class, you can use `in >> boolalpha >> b`

2020-12-28 04:32 UTC, Pterosaur commented on common/stringutility.h
> +// static inline void lexical_convert(const std::string &str, bool &b)
Yes, it will call the default one. But I cannot understand why we need a special overload lexical_convert for AlphaBoolean?

2020-12-28 06:15 UTC, qiluo-msft commented on common/boolean.h
> +    operator bool() const
>operator bool() [](start = 4, length = 15)

You need another cast operator
```
    operator bool&()
    {
        return m_boolean;
    }
```

2020-12-28 06:44 UTC, qiluo-msft approved these changes

2020-12-29 10:57 UTC, merged