[TableBase] Make channel name from both table name and database ID
Azure/sonic-swss-common pull request #568
Opened 2021-12-17 10:26 UTC by jimmyzhai

1. Same table name can be used in different databases, derive channel name from database ID too, since pub/sub works globally on all databases.
2. Always get separator from SonicDBConfig, done in TableBase constructor internal.
3. Remove the deprecated tableNameSeparatorMap

2021-12-18 04:02 UTC, qiluo-msft commented on common/table.h
> -    __attribute__((deprecated))
>deprecated [](http://example.com/codeflow?start=19&length=10)

Please don't remove `deprecated` attribute. The reason is we are using tableName to identify a table. And the deprecated ctor is only used in SWIG, and then used by old test code, which we did not migrate completely.

2021-12-18 04:17 UTC, qiluo-msft commented on common/table.h
> +    std::string getChannelName() { return m_tableName + "_CHANNEL"
>getChannelName [](http://example.com/codeflow?start=16&length=14)

The dbId is a concept out of TableBase class.
Could you add new parameter `dbId`, and do not use a member?

2021-12-18 04:18 UTC, qiluo-msft requested changes
As comments

2021-12-28 10:47 UTC, jimmyzhai commented on common/table.h
> -    __attribute__((deprecated))
Looks `dbId` is widely used to identify a database, and both `Id` and `Name` are primary properties of database.  In database domain hierarchy, table always belongs to one database. To add `dbId` member in class TableBase is meaningful to indicate in which database the table is. In ctor internal, table separator is initialized to the separator of  database `dbId`.

2021-12-28 10:47 UTC, jimmyzhai commented on common/table.h
> +    std::string getChannelName() { return m_tableName + "_CHANNEL"
As above reply,  I thinking adding `dbId` as a member is much reasonable.

2021-12-29 02:49 UTC, qiluo-msft commented on common/table.h
> -    TableBase(const std::string &tableName, const std::string &tableSeparator)
>TableBase [](http://example.com/codeflow?start=4&length=9)

In the design of `database_config.json`, the mapping is dbName -> (dbId, tableSeparator, dbInstance). So there is possible usage that multiple dbNames mapped to the same dbId, but with different tableSeparator.

This ctor is used by many C++ subclasses. In all use cases, the separator are deduced from dbName. The function `getSeparator(int dbId, const string &netns)` is only used in SWIG and python vstest. In future, the vstest code will not use dbId directly, and this function will be deprecated.

2021-12-29 02:51 UTC, qiluo-msft commented on common/table.cpp
> -// NOTE: this map is deprecated and will be removed in the future, and new DBs should instead be added to database_config.json
>deprecated [](http://example.com/codeflow?start=21&length=10)

As the comment, this logic is used by some application depending on SWIG swsscommon library. As far as I know, some python vstest are still not using database_config.json and use old dbId. To migrate all of them to use dbName instead of dbId is a long effort.

So if you are stick with this solution, please check the vstest failures.

2022-01-04 07:56 UTC, jimmyzhai commented on common/table.h
> -    TableBase(const std::string &tableName, const std::string &tableSeparator)
Sure, need to consider the case of 'multiple dbNames mapped to the same dbId, but with different tableSeparator'

2022-01-04 09:25 UTC, jimmyzhai commented on common/table.cpp
> -// NOTE: this map is deprecated and will be removed in the future, and new DBs should instead be added to database_config.json
I'll use the approach to adding a new overload function of getChannelName with param `tag`.

2022-01-04 20:17 UTC, qiluo-msft commented on common/producertable.cpp
> +        getChannelName(m_pipe->getDbName()).c_str(),
>getDbName [](http://example.com/codeflow?start=31&length=9)

Better to use `getDbId()` as a tag. It is possible that a `DBConnector` has empty dbName. And this is true with old vstest code written in python, using SWIG swsscommon.

2022-01-05 09:52 UTC, jimmyzhai commented on common/producertable.cpp
> +        getChannelName(m_pipe->getDbName()).c_str(),
Yes, correct it

2022-01-06 07:08 UTC, qiluo-msft commented on common/notificationproducer.cpp
>  swss::NotificationProducer::NotificationProducer(swss::DBConnector *db, const std::string &channel):
>NotificationProducer [](http://example.com/codeflow?start=28&length=20)

Do you need to change NotificationConsumer accordingly?

2022-01-11 01:33 UTC, jimmyzhai commented
/azp run

2022-01-12 02:40 UTC, qiluo-msft approved these changes

2022-01-12 03:17 UTC, jimmyzhai commented
/azp run

2022-01-12 09:10 UTC, jimmyzhai commented
/azp run

2022-01-13 07:58 UTC, jimmyzhai commented on common/notificationproducer.cpp
>  swss::NotificationProducer::NotificationProducer(swss::DBConnector *db, const std::string &channel):
Updated. Hold on the change of channel name tagged dbId for Notification Producer/Consumer. Some lua scripts like pfc_restore.lua, pfe_detect are using redis `PUBLISH` command directly with hardcode channel name.

2022-01-13 19:36 UTC, qiluo-msft approved these changes

2022-01-14 01:05 UTC, merged