Add a new constructor to NotificationConsumer class.
Azure/sonic-swss-common pull request #579
Opened 2022-01-26 12:50 UTC by oleksandrivantsiv

Add a new constructor that takes a shared pointer to DBConnector as a parameter.
The constructor will be used when the DBConnector object is shared across
different consumers objects. Or when DBConnector is created exclusively for one
consumer and consumer is responsible for the destruction of DBConnector object.

2022-01-26 17:21 UTC, dgsudharsan approved these changes

2022-01-27 11:55 UTC, liat-grozovik commented
/azp run Azure.sonic-swss-common

2022-02-08 09:56 UTC, oleksandrivantsiv commented
/azp run Azure.sonic-swss-common

2022-02-09 15:43 UTC, dgsudharsan approved these changes

2022-02-09 15:45 UTC, dgsudharsan approved these changes

2022-02-20 14:20 UTC, liat-grozovik commented
@qiluo-msft could you please help to review?

2022-02-24 10:52 UTC, liat-grozovik commented
@kcudnik , @qiluo-msft kindly reminder to review and signoff.

2022-02-24 12:37 UTC, kcudnik approved these changes

2022-02-28 06:15 UTC, qiluo-msft commented
>             delete m_subscribe;

if m_db == m_db_shrd, they point to the same object. We should never delete it, right?

---
Refers to: common/notificationconsumer.cpp:45 in 603c458. [](commit_id = 603c4580277228dc60f4b010b897993edb7e877d, deletion_comment = False)

2022-02-28 06:15 UTC, qiluo-msft commented
>     delete m_subscribe;

The same question.

---
Refers to: common/notificationconsumer.cpp:54 in 603c458. [](commit_id = 603c4580277228dc60f4b010b897993edb7e877d, deletion_comment = False)

2022-02-28 06:16 UTC, qiluo-msft requested changes
As comments

2022-03-02 17:35 UTC, oleksandrivantsiv commented
> if m_db == m_db_shrd, they point to the same object. We should never delete it, right?

This PR modifies behavior of **m_db** pointer. **m_db** should never be deleted. It is controlled via **m_db_shrd**
Here you are referring to **m_subscribe** pointer which is an internal member that is controlled by NotificationConsumer. It is completely independent of **m_db** and should always be deleted.

2022-03-02 17:37 UTC, oleksandrivantsiv commented
> > ```
> > delete m_subscribe;
> > ```
> 
> The same question.
> 
> Refers to: common/notificationconsumer.cpp:54 in [603c458](https://github.com/Azure/sonic-swss-common/commit/603c4580277228dc60f4b010b897993edb7e877d). [](commit_id = [603c458](https://github.com/Azure/sonic-swss-common/commit/603c4580277228dc60f4b010b897993edb7e877d), deletion_comment = False)

**m_subscribe** is owned by NotificationConsumer and should always be deleted

2022-03-02 17:40 UTC, oleksandrivantsiv commented
@qiluo-msft kindly ask to take a look to my answer

2022-03-05 00:25 UTC, qiluo-msft commented on common/notificationconsumer.cpp
> +swss::NotificationConsumer::NotificationConsumer(std::shared_ptr<swss::DBConnector> db, const std::string &channel, int pri, size_t popBatchSize):
>NotificationConsumer [](http://example.com/codeflow?start=28&length=20)

I am wondering why this is needed in common library. You are good to use original constructor as, and it behaves the same.
```
swss::NotificationConsumer nc(dbNtf.get(), "NOTIFICATIONS", 100, (size_t)messages);
```

2022-03-17 15:29 UTC, oleksandrivantsiv commented
Closing this PR as we found a better way to trigger address sanitizer to report only memory that is definitely lost.

2022-03-17 15:29 UTC, closed without merging