[MSTP] Schema Support
Azure/sonic-swss-common pull request #961
Opened 2024-12-17 09:22 UTC by wajahatrazi

2024-12-17 09:22 UTC, mssonicbld commented
/azp run

2024-12-22 19:55 UTC, mssonicbld commented
/azp run

2025-02-11 13:07 UTC, divyachandralekha requested changes

2025-02-11 13:07 UTC, divyachandralekha commented on common/schema.h
> +
Please rename the tables as below

#define APP_STP_MST_TABLE_NAME              "STP_MST_INST_TABLE"
#define APP_STP_MST_PORT_TABLE_NAME         "STP_MST_PORT_TABLE"
#define [APP_STP_INST_PORT_FLUSH_TABLE_NAME "STP_INST_PORT_FLUSH_TABLE"

2025-03-10 09:32 UTC, mssonicbld commented
/azp run

2025-04-15 05:43 UTC, mssonicbld commented
/azp run

2025-04-22 04:34 UTC, mssonicbld commented
/azp run

2025-04-24 16:11 UTC, mssonicbld commented
/azp run

2025-04-24 16:12 UTC, divyachandralekha commented
Please follow up the build issue.

2025-04-29 07:07 UTC, divyachandralekha commented
Please move the PR to official

2025-05-05 14:00 UTC, prhoskot approved these changes

2025-07-10 05:51 UTC, mssonicbld commented
/azp run

2025-07-14 09:39 UTC, divyachandralekha commented
@lguohan , Please merge the changes

2025-07-14 17:16 UTC, divyachandralekha commented
/AzurePipelines run Azure.sonic-swss-common

2025-07-14 17:16 UTC, divyachandralekha commented
/azpw run Azure.sonic-swss-common

2025-07-14 17:16 UTC, mssonicbld commented
/AzurePipelines run Azure.sonic-swss-common

2025-07-15 05:47 UTC, muhammadalihussnain commented on common/schema.h
> +
Renamed the tables

2025-07-15 05:49 UTC, muhammadalihussnain commented on common/schema.h
> +
extra lines removed

2025-07-15 05:49 UTC, mssonicbld commented
/azp run

2025-07-15 08:12 UTC, mssonicbld commented
/azp run

2025-07-15 10:02 UTC, mssonicbld commented
/azp run

2025-07-15 16:49 UTC, mssonicbld commented
/azp run

2025-07-18 10:33 UTC, mssonicbld commented
/azp run

2025-07-21 19:40 UTC, sutharsansr approved these changes

2025-07-23 10:55 UTC, mssonicbld commented
/azp run

2025-07-23 11:00 UTC, mssonicbld commented
/azp run

2025-07-23 11:51 UTC, mssonicbld commented
/azp run

2025-07-25 05:58 UTC, muhammadalihussnain commented
@lguohan , Please merge the changes

2025-07-25 21:28 UTC, mssonicbld commented
/azp run

2025-07-28 04:41 UTC, divyachandralekha commented
/azpw run Azure.sonic-swss-common

2025-07-28 04:41 UTC, mssonicbld commented
/AzurePipelines run Azure.sonic-swss-common

2025-07-30 12:03 UTC, muhammadalihussnain commented
/azpw run Azure.sonic-swss-common

2025-07-30 12:03 UTC, mssonicbld commented
/AzurePipelines run Azure.sonic-swss-common

2025-07-30 16:01 UTC, muhammadalihussnain commented
@lguohan @qiluo-msft  Please merge the changes

2025-07-30 18:10 UTC, qiluo-msft commented
@wajahatrazi The latest commit made this PR an empty change. Could you check?

2025-07-30 18:16 UTC, mssonicbld commented
/azp run

2025-07-30 18:17 UTC, mssonicbld commented
/azp run

2025-07-30 18:56 UTC, mssonicbld commented
/azp run

2025-07-30 21:34 UTC, muhammadalihussnain commented
/azpw run Azure.sonic-swss-common

2025-07-30 21:34 UTC, mssonicbld commented
/AzurePipelines run Azure.sonic-swss-common

2025-07-31 07:41 UTC, mssonicbld commented
/azp run

2025-07-31 08:04 UTC, muhammadalihussnain commented
/azpw run Azure.sonic-swss-common

2025-07-31 08:04 UTC, mssonicbld commented
/AzurePipelines run Azure.sonic-swss-common

2025-07-31 08:29 UTC, mssonicbld commented
/azp run

2025-07-31 09:14 UTC, mssonicbld commented
/azp run

2025-07-31 12:12 UTC, mssonicbld commented
/azp run

2025-07-31 12:37 UTC, mssonicbld commented
/azp run

2025-07-31 13:00 UTC, mssonicbld commented
/azp run

2025-07-31 13:32 UTC, mssonicbld commented
/azp run

2025-07-31 13:38 UTC, mssonicbld commented
/azp run

2025-07-31 18:13 UTC, muhammadalihussnain commented
@qiluo-msft Please merge the changes

2025-07-31 21:55 UTC, qiluo-msft approved these changes

2025-07-31 21:55 UTC, merged